export const ACTION_TYPE = {
  INITIALIZE_PRODUCTS: 'INITIALIZE_PRODUCTS',
  INITIALIZE_CATEGORIES: 'INITIALIZE_CATEGORIES',
  FILTER_CHANGE: 'FILTER_CHANGE',
  CLEAR_FILTER: 'CLEAR_FILTER',
  SEARCH_FILTER: 'SEARCH_FILTER',
  SETCART_LIST: 'SETCART_LIST',
  WISHLIST: 'WISHLIST',
  CLEAR_CART: 'CLEAR_CART',
  ADDRESS: 'ADDRESS',
  DELETE_ADDRESS: 'DELETE_ADDRESS',
};
